[build-system]
requires = ["abc", "typing", "collections", "asyncio"]
build-backend = "pyholon.build"
[project]
name = "pyholon"
version = "0.0.1"
authors = [
  { name="Henrique Emanoel Viana", email="hv5088@gmail.com" },
]
description = "The Notification Oriented Paradigm (NOP), in addition to avoiding temporal and structural code redundancies through notifications, has a defined inference model. This framework promotes flexibility of this inference model. This flexibility is provided by a standardized structure for notifying processing, named Notifying Holon."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering"
]
[project.urls]
"Homepage" = "https://github.com/hviana/pyHolon"